# Generated by Django 5.0.4 on 2024-04-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='service_type',
        ),
        migrations.AddField(
            model_name='case',
            name='service_type',
            field=models.CharField(blank=True, choices=[('web', 'Web Development'), ('mobile', 'Mobile App Development'), ('software', 'Software Development')], max_length=100),
        ),
    ]
