# Generated by Django 4.0.3 on 2024-04-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='country_image',
            field=models.ImageField(blank=True, null=True, upload_to='case/'),
        ),
    ]
