# Generated by Django 5.0.4 on 2024-05-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_pricingestimate_additional_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingestimate',
            name='additional_features',
            field=models.CharField(blank=True, choices=[('messaging', 'Messaging'), ('geolocation', 'Geolocation'), ('shopping_cart', 'Shopping Cart & Orders History'), ('cms', 'Basic CMS for Content Uploading'), ('bluetooth', 'Bluetooth Connectivity'), ('camera', 'Camera (QR Code Scanning)'), ('multi_language', 'Multi-language Support'), ('social_media', 'Social Media Sharing')], max_length=100),
        ),
    ]
