# Generated by Django 5.0.4 on 2024-05-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_case_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='assigned_to',
        ),
    ]
