# Generated by Django 4.0.3 on 2024-03-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_blogpost_category_companyinformation_contactinquiry_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserorAuther',
            new_name='Auther',
        ),
    ]
