# Generated by Django 5.0.4 on 2024-05-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_case_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='heading',
            new_name='description',
        ),
    ]
