# Generated by Django 5.0.4 on 2024-04-30 11:17

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_case_service_type_case_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='industries',
        ),
        migrations.AddField(
            model_name='case',
            name='industries',
            field=models.TextField(blank=True, verbose_name=account.models.Industrie),
        ),
    ]
