# Generated by Django 4.0.3 on 2024-04-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_case_country_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Author_image',
            field=models.ImageField(blank=True, null=True, upload_to='Auther_images/'),
        ),
    ]
