# Generated by Django 4.0.3 on 2024-04-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='ContactInquiry',
            new_name='ContactInquirie',
        ),
        migrations.RenameModel(
            old_name='Technology',
            new_name='Technologie',
        ),
    ]
