# Generated by Django 4.0.3 on 2024-03-25 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_userorauther_auther'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client_testimonials',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies_used',
        ),
    ]
