# Generated by Django 4.0.3 on 2024-04-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_blogpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='resolution',
        ),
    ]
