# Generated by Django 4.0.3 on 2024-04-23 10:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_author_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='heading',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Heading_Content'),
        ),
    ]
