# Generated by Django 5.0.4 on 2024-04-30 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_case_industries_case_industries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='industries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='account.industrie'),
        ),
    ]
