# Generated by Django 5.0.4 on 2024-06-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_privacypolicy_termsandconditions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='case_multiple_images/')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_images', to='account.case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='multiple_images',
            field=models.ManyToManyField(blank=True, related_name='cases', to='account.caseimage'),
        ),
    ]
