# Generated by Django 4.0.3 on 2024-04-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_qna'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qna',
            old_name='answer',
            new_name='Answer',
        ),
        migrations.RenameField(
            model_name='qna',
            old_name='question',
            new_name='Question',
        ),
    ]
