# Generated by Django 4.0.3 on 2024-03-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_project_categories_project_technologies_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies_used',
        ),
    ]
