# Generated by Django 4.0.3 on 2024-04-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile App Development'), ('software', 'Software Development')], max_length=100)),
                ('feature_set', models.TextField(help_text='Detailed description of the requested features')),
                ('complexity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('estimated_hours', models.DecimalField(decimal_places=2, help_text='Estimated hours to complete the project', max_digits=6)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate for the service', max_digits=10)),
                ('additional_costs', models.DecimalField(decimal_places=2, default=0, help_text='Additional costs', max_digits=10)),
                ('discounts', models.DecimalField(decimal_places=2, default=0, help_text='Discounts applied', max_digits=10)),
                ('total_estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Automatically calculated total cost', max_digits=10, null=True)),
                ('client_information', models.CharField(help_text='Information about the client', max_length=255)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', help_text='Status of the estimate', max_length=100)),
            ],
            options={
                'verbose_name': 'Pricing Estimate',
                'verbose_name_plural': 'Pricing Estimates',
                'ordering': ['-submitted_on'],
            },
        ),
    ]
