# Generated by Django 4.0.3 on 2024-04-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_answer_qna_answer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QnA',
            new_name='QuestionsAnswer',
        ),
    ]
