# Generated by Django 4.0.3 on 2024-04-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_qna_questionsanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_member_images/'),
        ),
    ]
