# Generated by Django 4.0.3 on 2024-03-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='primary_technologies',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='projects', to='account.technology'),
        ),
    ]
