# Generated by Django 4.0.3 on 2024-03-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_project_primary_technologies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='primary_technologies',
        ),
    ]
